// Illustrative starter catalogue, not manufacturer fitment advice or market pricing.
// Existing SKUs, prices and stock are never overwritten by catalogue import.
export const catalogue = [
  ['OIL-10W30', 'Engine oil · 1 litre', 'Fluids', 'bottle', 450],
  ['OIL-5W30', 'Engine oil 5W-30 · 1 litre', 'Fluids', 'bottle', 650],
  ['GEAR-OIL', 'Gear oil · 1 litre', 'Fluids', 'bottle', 400],
  ['BRAKE-FLUID', 'Brake fluid DOT 4 · 500 ml', 'Fluids', 'bottle', 280],
  ['COOLANT', 'Ready-mix coolant · 1 litre', 'Fluids', 'bottle', 350],
  ['CHAIN-LUBE', 'Chain lubricant · 400 ml', 'Fluids', 'can', 320],
  ['GREASE', 'Multipurpose grease · 500 g', 'Fluids', 'tub', 220],
  ['FLT-001', 'Oil filter', 'Filters', 'unit', 180],
  ['AIR-001', 'Air filter', 'Filters', 'unit', 320],
  ['CABIN-FLT', 'Cabin air filter', 'Filters', 'unit', 450],
  ['FUEL-FLT', 'Fuel filter', 'Filters', 'unit', 350],
  ['BRK-001', 'Front brake pad set', 'Brakes', 'set', 850],
  ['BRK-REAR', 'Rear brake shoe set', 'Brakes', 'set', 650],
  ['BRK-DISC', 'Brake disc', 'Brakes', 'unit', 1800],
  ['TYRE-2W-F', 'Two-wheeler front tyre', 'Tyres', 'unit', 1600],
  ['TYRE-2W-R', 'Two-wheeler rear tyre', 'Tyres', 'unit', 2000],
  ['TYRE-CAR', 'Passenger-car tyre', 'Tyres', 'unit', 4500],
  ['TUBE-2W', 'Two-wheeler inner tube', 'Tyres', 'unit', 350],
  ['VALVE-TYRE', 'Tyre valve', 'Tyres', 'unit', 80],
  ['SPARK-PLUG', 'Spark plug', 'Electrical', 'unit', 220],
  ['BATTERY-12V', '12 V auxiliary battery', 'Electrical', 'unit', 4200],
  ['HEADLAMP', 'Headlamp bulb', 'Electrical', 'unit', 300],
  ['FUSE-SET', 'Automotive fuse kit', 'Electrical', 'set', 180],
  ['HORN', 'Horn assembly', 'Electrical', 'unit', 550],
  ['CHAIN-KIT', 'Drive chain and sprocket kit', 'Drivetrain', 'set', 1800],
  ['CLUTCH-CABLE', 'Clutch cable', 'Drivetrain', 'unit', 250],
  ['CLUTCH-PLATE', 'Clutch plate kit', 'Drivetrain', 'set', 2200],
  ['DRIVE-BELT', 'Drive belt', 'Drivetrain', 'unit', 950],
  ['WIPER-SET', 'Wiper blade pair', 'Body & cabin', 'pair', 700],
  ['WHEEL-BEARING', 'Wheel bearing', 'Suspension', 'unit', 650],
  ['FORK-SEAL', 'Fork oil seal kit', 'Suspension', 'set', 350],
  ['DRAIN-WASHER', 'Drain-plug washer', 'Consumables', 'unit', 25],
  ['CABLE-TIE', 'Cable tie pack', 'Consumables', 'pack', 100],
  ['EV-PORT-CAP', 'EV charge-port dust cap', 'EV accessories', 'unit', 300],
  ['EV-CABIN-FLT', 'EV cabin filter', 'EV accessories', 'unit', 550],
  ['EV-COOLANT', 'EV-compatible coolant · 1 litre', 'EV accessories', 'bottle', 800],
].map(([sku, name, category, unit, price]) => ({
  sku,
  name,
  category,
  unit,
  pricePaise: price * 100,
  stock: 0,
  minimum: 3,
  compatibility: 'Confirm model, size and manufacturer specification before use',
}));
